//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpdateNWDeviceStatus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapNetMonEntities : DbContext
    {
        public MapNetMonEntities()
            : base("name=MapNetMonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TM_Type> TM_Type { get; set; }
        public DbSet<TM_Factory> TM_Factory { get; set; }
        public DbSet<VW_Emp_Admin> VW_Emp_Admin { get; set; }
        public DbSet<TD_Device> TD_Device { get; set; }
        public DbSet<TD_DeadTransaction> TD_DeadTransaction { get; set; }
    }
}
