//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpdateNWDeviceStatus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_DeadTransaction
    {
        public string IP { get; set; }
        public System.DateTime DeadDate { get; set; }
        public Nullable<System.DateTime> RebornDate { get; set; }
    
        public virtual TD_Device TD_Device { get; set; }
    }
}
