//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpdateNWDeviceStatus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Factory
    {
        public TM_Factory()
        {
            this.TD_Device = new HashSet<TD_Device>();
        }
    
        public byte Id { get; set; }
        public byte PlantId { get; set; }
        public string Name { get; set; }
        public string Img { get; set; }
    
        public virtual ICollection<TD_Device> TD_Device { get; set; }
    }
}
