//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNetworkMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Device
    {
        public TD_Device()
        {
            this.TD_Neighbor = new HashSet<TD_Neighbor>();
            this.TD_DeadTransaction = new HashSet<TD_DeadTransaction>();
        }
    
        public string IP { get; set; }
        public short Type { get; set; }
        public byte FactoryId { get; set; }
        public string Name { get; set; }
        public bool MainDevice { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public Nullable<int> XMain { get; set; }
        public Nullable<int> YMain { get; set; }
        public string ConfigFile { get; set; }
        public string UplinkIP { get; set; }
        public string UplinkPort { get; set; }
        public Nullable<System.DateTime> LastOn { get; set; }
        public bool Status { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual TM_Status TM_Status { get; set; }
        public virtual TM_Type TM_Type { get; set; }
        public virtual TM_Factory TM_Factory { get; set; }
        public virtual ICollection<TD_Neighbor> TD_Neighbor { get; set; }
        public virtual ICollection<TD_DeadTransaction> TD_DeadTransaction { get; set; }
    }
}
