//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNetworkMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Neighbor
    {
        public string IP { get; set; }
        public string NIP { get; set; }
        public string AnchorA { get; set; }
        public string AnchorB { get; set; }
    
        public virtual TD_Device TD_Device { get; set; }
    }
}
