//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNetworkMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Command
    {
        public short Id { get; set; }
        public short TypeId { get; set; }
        public string Name { get; set; }
        public string Command { get; set; }
    
        public virtual TM_Type TM_Type { get; set; }
    }
}
