//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNetworkMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Plant
    {
        public TM_Plant()
        {
            this.TM_Factory = new HashSet<TM_Factory>();
        }
    
        public byte Id { get; set; }
        public string Name { get; set; }
        public string Img { get; set; }
    
        public virtual ICollection<TM_Factory> TM_Factory { get; set; }
    }
}
