//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNetworkMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Predefined
    {
        public int BGWidth { get; set; }
        public double FontSize { get; set; }
        public byte LineWidth { get; set; }
        public string LineColor { get; set; }
        public string Unit { get; set; }
        public string ParentHilightColor { get; set; }
        public string ChildHilightColor { get; set; }
        public int HilightDuration { get; set; }
    }
}
