//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapNetworkMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Device_Summary
    {
        public byte Id { get; set; }
        public string Site { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Up { get; set; }
        public Nullable<int> Down { get; set; }
    }
}
